sudo: required
dist: trusty
addons:
  apt:
    packages:
      - mysql-server-5.6
      - mysql-client-core-5.6
      - mysql-client-5.6
      - postfix
  firefox: "46.0"
  hosts:
    - magento2.travis
language: php
php:
   - 7.0
   - 7.1
env:
  global:
    - COMPOSER_BIN_DIR=~/bin
    - INTEGRATION_SETS=3
    - NODE_JS_VERSION=6
    - MAGENTO_HOST_NAME="magento2.travis"
    - TEST_COMPOSER_MODULE=mercadopago/magento2-plugin
  matrix:
    #- MAGENTO_VERSION=2.2.2 TEST_SUITE=unit
    #- MAGENTO_VERSION=2.2.2 TEST_SUITE=static
    #- MAGENTO_VERSION=2.2.2 TEST_SUITE=js GRUNT_COMMAND=spec
    #- MAGENTO_VERSION=2.2.2 TEST_SUITE=js GRUNT_COMMAND=static
    - MAGENTO_VERSION=2.2.2 TEST_SUITE=integration INTEGRATION_INDEX=1
    - MAGENTO_VERSION=2.2.2 TEST_SUITE=integration INTEGRATION_INDEX=2
    - MAGENTO_VERSION=2.2.2 TEST_SUITE=integration INTEGRATION_INDEX=3
    - MAGENTO_VERSION=2.2.2 TEST_SUITE=functional
    - MAGENTO_VERSION=2.2.3 TEST_SUITE=unit
    - MAGENTO_VERSION=2.2.3 TEST_SUITE=static
    - MAGENTO_VERSION=2.2.3 TEST_SUITE=js GRUNT_COMMAND=spec
    - MAGENTO_VERSION=2.2.3 TEST_SUITE=js GRUNT_COMMAND=static
    - MAGENTO_VERSION=2.2.3 TEST_SUITE=integration INTEGRATION_INDEX=1
    - MAGENTO_VERSION=2.2.3 TEST_SUITE=integration INTEGRATION_INDEX=2
    - MAGENTO_VERSION=2.2.3 TEST_SUITE=integration INTEGRATION_INDEX=3
    - MAGENTO_VERSION=2.2.3 TEST_SUITE=functional
matrix:
  exclude:
    - php: 7.0
      env: MAGENTO_VERSION=2.2.3 TEST_SUITE=static
    - php: 7.0
      env: MAGENTO_VERSION=2.2.3 TEST_SUITE=js GRUNT_COMMAND=spec
    - php: 7.0
      env: MAGENTO_VERSION=2.2.3 TEST_SUITE=js GRUNT_COMMAND=static
    - php: 7.0
      env: MAGENTO_VERSION=2.2.2 TEST_SUITE=functional
    - php: 7.0
      env: MAGENTO_VERSION=2.2.3 TEST_SUITE=functional
cache:
  apt: true
  directories:
    - $HOME/.composer/cache
    - $HOME/.nvm
    - $HOME/node_modules
    - $HOME/yarn.lock
before_install:
  - git clone https://github.com/magento/magento2 --branch $MAGENTO_VERSION
  - cd ${TRAVIS_BUILD_DIR}/magento2
  - ./dev/travis/before_install.sh
install:
  - composer config minimum-stability dev
  - composer install --no-interaction --prefer-dist
  - composer config repositories.test_target git https://github.com/${TRAVIS_REPO_SLUG}.git
  - composer require $COMPOSER_TEST_MODULE dev-$TRAVIS_BRANCH
before_script:
  - ./dev/travis/before_script.sh
script:
  # Set arguments for variants of phpunit based tests; '|| true' prevents failing script when leading test fails
  - test $TEST_SUITE = "functional" && TEST_FILTER='dev/tests/functional/testsuites/Magento/Mtf/TestSuite/InjectableTests.php' || true

  # The scripts for grunt/phpunit type tests
  - if [ $TEST_SUITE == "functional" ]; then dev/tests/functional/vendor/phpunit/phpunit/phpunit -c dev/tests/$TEST_SUITE $TEST_FILTER; fi
  - if [ $TEST_SUITE != "functional" ] && [ $TEST_SUITE != "js" ]; then phpunit -c dev/tests/$TEST_SUITE $TEST_FILTER; fi
  - if [ $TEST_SUITE == "js" ]; then grunt $GRUNT_COMMAND; fi